# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json
PackageIdentifier: TMHSDigital.WindowsAutoclicker
PackageVersion: 1.5.0
InstallerType: portable
Commands:
- autoclicker
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/TMHSDigital/autoclicker/releases/download/v1.5.0/WindowsAutoclicker.exe
  InstallerSha256: EA174ABCABA33EBCF0C30E60A783B4802FBF3526F415065AA1E416EB6034F9A5
ManifestType: installer
ManifestVersion: 1.12.0
